spring:
  cloud:
    gateway:
      routes: # 路由配置
        - id: test_route # 路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: https://www.baidu.com # 匹配后提供服务的路由地址
          predicates: # 断言，路由的条件
            - Query=url, baidu # 配置了此参数，请求必须带有url参数且值为baidu，才能访问该路由
        - id: test_route2
          uri: https://www.jd.com
          predicates:
            - Query=url, jd
